

name: IdeaCenter

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ExamPrepIdeaCenter.csproj

      - name: Build
        run: dotnet build ExamPrepIdeaCenter.csproj --no-restore

      - name: Test
        run: dotnet test ExamPrepIdeaCenter.csproj --no-build
